
import { StyleSheet } from 'react-native'

export const customStyles = StyleSheet.create({
    loginContainer: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
        padding: 10,
        backgroundColor: '#FFFFFF',
    },
    signUpContainer: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
        padding: 5,
        backgroundColor: '#FFFFFF',
    },
    title: {
        fontSize: 20,  
        marginBottom: 20,
        marginTop: 0,
        color: '#53affa',
        alignItems: 'center',
        marginTop: 25,
        fontWeight: 'bold', 
        textAlign: 'center',
    },
    input: {
        width: '90%',
        padding: 10,
        marginVertical: 10,
        borderWidth: 1,
        borderRadius: 15,
        borderColor: '#ccc',
        color:'#000',
    },
    datePicker:{
        width: '30%',
        padding: 10,
        marginVertical: 10,
        borderWidth: 1,
        borderRadius: 15,
        borderColor: '#ccc',
        justifyContent:'center' 
    },
    rgInput: {
        width: '68%',
        padding: 10,
        marginVertical: 10,
        borderWidth: 1,
        borderRadius: 15,
        borderColor: '#ccc',
        color:'#000',
    },
    button: {
        backgroundColor: '#007BFF',
        padding: 10,
        borderRadius: 8,
        width: '100%',
        alignItems: 'center',
        marginVertical: 10,
    },
    buttonText: {
        color: '#fff',
        fontSize: 16,
    },
    link: {
        color: '#007BFF',
        marginTop: 10,
    },
    buttonSubmit: {
        padding: 12,
        borderRadius: 8,
        alignItems: 'center',
        borderRadius: 20,
        width: '90%',
        backgroundColor: '#0071CF',
        marginVertical:'5%',
    },
    textSubmit: {  
        color: 'white', 
        fontWeight: 'bold'
    },
    row: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        width: '90%',
    },
    link: {
        color: '#007BFF',
        marginTop: 10,
    },
    datePickerText:{
       color: '#616161',

    },
    footer: {
        flexDirection: 'row',
        justifyContent: 'space-around',
        alignItems: 'center',
        padding: 10,
        backgroundColor: '#003770',
        position: 'absolute',
        bottom: 0,
        width: '100%',
    },
    receitaButton: {
        flexDirection: 'row',
        justifyContent: 'center',
        alignItems: 'center',
        backgroundColor: '#4CAF50',
        borderRadius: 10,
        paddingVertical: 10,
        paddingHorizontal: 15,
    },
    receitaButtonText: {
        color: 'white',
        fontSize: 16,
        marginLeft: 5,
    },
    logoutButton: {
        backgroundColor: '#FF5722',
        borderRadius: 10,
        paddingVertical: 10,
        paddingHorizontal: 15,
    },
    logoutButtonText: {
        color: 'white',
        fontSize: 16,
    },
    modalContainer: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
        backgroundColor: 'rgba(0,0,0,0.5)',
    },
    modalContent: {
        width: 300,
        padding: 20,
        backgroundColor: 'white',
        borderRadius: 10,
        alignItems: 'center',
    },
    modalTitle: {
        fontSize: 18,
        fontWeight: 'bold',
        marginBottom: 10,
    },
    inputChat: {
        width: '100%',
        borderWidth: 1,
        borderColor: '#ccc',
        borderRadius: 5,
        padding: 10,
        marginBottom: 20,
    },
    formView:{
        flex: 1, 
        backgroundColor: 'white', 
        padding: 15,
        alignItems: 'center',
    },
    formTextBlue:{
        fontSize: 20,  
        marginBottom: 20,
        marginTop: 10,
        color: '#53affa',
        alignItems: 'center',
        marginTop: 25,
        fontWeight: 'bold', 
        textAlign: 'center',
    },
    formInput: {
        borderWidth: 1,
        borderColor: '#ccc',
        borderRadius: 15,
        padding: 8,
        marginBottom: 16,
        marginTop: 25,
        width: '90%',
    },
    formInputObs: {
        borderWidth: 1,
        borderColor: '#ccc',
        borderRadius: 15,
        padding: 8,
        marginBottom: 16,
        textAlignVertical: 'top',
        marginTop: 30,
        height: 120,
        width: '90%',
    },
    textInfo: {
        fontSize: 12,
        color: 'red',
        textAlign: 'center',
        width: '90%',
        marginTop: 30,
    },
    confirmBtn:{
        padding: 12,
        borderRadius: 8,
        alignItems: 'center',
        borderRadius: 20,
        width: '90%',
        backgroundColor: '#0071CF',
        marginVertical: 10,
    },
    confirmBtnText:{
        color: 'white', 
        fontWeight: 'bold'
    },
    loadingContainer: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
        backgroundColor: '#FFFFFF',
    },
    loadingText: {
        fontSize: 18,
        marginVertical: 5,
    },
    container: {
        flex: 1,
        backgroundColor: '#fff',
        paddingHorizontal: 16,
        paddingTop: 16,
    },
    header: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginBottom: '30%',
    },
    greeting: {
        fontSize: 24,
        fontWeight: 'bold',
        color: '#53affa',
        textAlign: 'center',

    },
    buttonContainer: {
        flexDirection: 'row',
        flexWrap: 'wrap',
        justifyContent: 'space-between',
        flex: 0.3,
    },
    Homebutton: {
        width: '45%',
        backgroundColor: '#FFFFFF',
        borderRadius: 8,
        marginBottom: 16,
        paddingVertical: 16,
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        elevation: 4, // Sombra no Android
        shadowColor: '#000', // Sombra no iOS
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.2,
        shadowRadius: 4,
        height: '50%',
        width: '49%',
        padding: '5%'
    },
    HomebuttonText: {
        fontSize: 16,
        fontWeight: '600',
        color: '#333',
        marginTop: 8,
        textAlign: 'center',
        marginRight: '15%',
        flex: 1,    
        textAlign: 'left',
    },
    profileIcon: {
        padding: 8,
    },
    waitRoomContainer: {
        flex: 1,
        padding: 10,
        backgroundColor: '#FFFFFF',
    },
    pacienteContainer: {
        padding: 15,
        marginVertical: 10,
        backgroundColor: '#fff',
        borderRadius: 8,
        borderColor: '#ccc',
        borderWidth: 1,
    },
    pacienteNome: {
        fontSize: 16,
        fontWeight: 'bold',
        color:'#555'
    },
    pacienteSusCard: {
        fontSize: 14,
        color: '#555',
        marginVertical: 2,
    },
    refreshButtonContainer: {
        position: 'absolute',
        bottom: 20,
        left: '90%',
        alignItems: 'center',
        justifyContent: 'center',
    },
    refreshButton: {
        backgroundColor: '#007BFF',
        padding: 10,
        borderRadius: 25,
    },
    refreshIcon: {
        borderRadius: 8,
    },
    notificationBadge: {
        position: 'absolute',
        top: -5,
        right: -5,
        backgroundColor: 'red',
        borderRadius: 10,
        width: 20,
        height: 20,
        alignItems: 'center',
        justifyContent: 'center',
    },
    notificationText: {
        color: 'white',
        fontSize: 12,
        fontWeight: 'bold',
    },
    pacienteCount: {
        fontSize: 20,  
        marginBottom: 20,
        marginTop: 10,
        color: '#53affa',
        alignItems: 'center',
        fontWeight: 'bold', 
        textAlign: 'center',
    },
    card: {
        backgroundColor: '#f9f9f9',
        padding: 15,
        marginVertical: 10,
        borderRadius: 8,
        borderColor: '#ddd',
        borderWidth: 1,
      },
      text: {
        fontSize: 16,
        marginBottom: 5,
      },
      bold: {
        fontWeight: 'bold',
      },
      sendButtonContainer: {
        justifyContent: 'center',
        alignItems: 'center',
        height: 44,
        width: 44,
        marginHorizontal: 10,
        marginBottom: 5,
    },
    sendButton: {
        backgroundColor: '#FFF',
        borderRadius: 22,
        height: 40,
        width: 40,
        justifyContent: 'center',
        alignItems: 'center',
    },
    endServiceButtonContainer: {
        flexDirection: "row",
        justifyContent: "space-around",
        alignItems: "center",
        padding: 10,
        backgroundColor: "#003770",
      },
    endServiceButton: {
        flexDirection: "row",
        alignItems: "center",
        backgroundColor: "#53affa",
        paddingVertical: 10,
        paddingHorizontal: 15,
        borderRadius: 5,
      },
    endServiceButtonText: {
        color: "#fff",
        marginLeft: 5,
        fontSize: 16,
      },
      pacienteObs: {
        fontSize: 14,
        color: '#666',
    },
});